######################################################################
# Automatically generated by qmake (3.0) Mon Jan 20 08:42:05 2020
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += mainwindow.h mainwidget.h
SOURCES += main.cpp mainwindow.cpp mainwidget.cpp
