######################################################################
# Automatically generated by qmake (3.0) Mon Jan 20 08:42:05 2020
######################################################################

TEMPLATE = app
TARGET = gui
INCLUDEPATH += .
INCLUDEPATH += ../toolpath/

QT += widgets

# Input
HEADERS += mainwindow.h mainwidget.h drawarea.h
SOURCES += main.cpp mainwindow.cpp mainwidget.cpp drawarea.cpp
LIBS += -lCGAL -lgmp -lCGAL_Core -lmpfr

